---
- name: Create elasticsearch directory
  file: 
    path: "{{ VAR_ELASTICSEARCH_DIR }}"
    recurse: yes
    state: directory

- name: Start elasticsearch container
  docker_container:
    name: elasticsearch 
    image: "elasticsearch:{{ VAR_ELASTICSEARCH_VERSION }}"
    pull: yes
    state: started
    env:
    - discovery.type=single-node   
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    labels:
      traefik.backend=grafana
      "traefik.frontend.rule=Host:{{ VAR_ELASTICSEARCH_URL }}"
      traefik.port=9200
      traefik.enable=true
    volumes:
    - "{{ VAR_ELASTICSEARCH_DIR }}:/usr/share/elasticsearch/data:z"
    restart_policy: unless-stopped

